// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef_pages_games_and_genres.Data;

#nullable disable

namespace ef_pages_games_and_genres.Migrations
{
    [DbContext(typeof(gameDbContext))]
    partial class gameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ef_pages_games_and_genres.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Name = "Doom"
                        },
                        new
                        {
                            GameId = 2,
                            Name = "Quake"
                        },
                        new
                        {
                            GameId = 3,
                            Name = "Final Fantasy"
                        },
                        new
                        {
                            GameId = 4,
                            Name = "Baldur's Gate"
                        },
                        new
                        {
                            GameId = 5,
                            Name = "Tetris"
                        },
                        new
                        {
                            GameId = 6,
                            Name = "Bejeweled"
                        });
                });

            modelBuilder.Entity("ef_pages_games_and_genres.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GameGenreId")
                        .IsUnique();

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenre");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1,
                            GameGenreId = 0
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 2,
                            GameGenreId = 0
                        });
                });

            modelBuilder.Entity("ef_pages_games_and_genres.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "RPG"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Puzzle"
                        });
                });

            modelBuilder.Entity("ef_pages_games_and_genres.Models.GameGenre", b =>
                {
                    b.HasOne("ef_pages_games_and_genres.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ef_pages_games_and_genres.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ef_pages_games_and_genres.Models.Game", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("ef_pages_games_and_genres.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
